### ISSUE TITLE
Error on TestGtRDFReader

### ISSUE THREAD

**Issue by franklarryx** [scify/JedAIToolkit#11]
Hi, I'm tried some tests with JedAI tool.
This tool is useful for my job and I think that it has big potentiality.
I've downloaded the attached file in nt format: source.nt, target.nt.
In the firts step I have successfully executed  TestRdfReader class presents in the test package for both datasets. After that I've tried to execute TestGtRDFReader class with the same datasets used before, but I have the following error:
`Exception in thread "main" java.lang.IllegalArgumentException: loops not allowed
	at org.jgrapht.graph.AbstractBaseGraph.addEdge(AbstractBaseGraph.java:203)
	at org.scify.jedai.datareader.groundtruthreader.GtRDFReader.performReading(GtRDFReader.java:236)
	at org.scify.jedai.datareader.groundtruthreader.GtRDFReader.getDuplicatePairs(GtRDFReader.java:92)
	at org.scify.jedai.datareader.groundtruthreader.AbstractGtReader.getDuplicatePairs(AbstractGtReader.java:57)
	at org.scify.jedai.datareader.TestGtRDFReader.main(TestGtRDFReader.java:39)`

[datasets.zip](https://github.com/scify/JedAIToolkit/files/2038653/datasets.zip)

Thanks in advance!

**Comment by franklarryx** [comment]
Hi, these datasets come from silkframework.org.
I have already checked that both datasets not contain any "sameAs" property.
I have debugged the code and seems that the issue is derivated from the following part of the code presents  in the GtRDFReader (line 229-234) class: 

`            final String sub = stmt.getSubject().toString();
            final String obj = stmt.getObject().toString();

            // add a new edge for every pair of duplicate entities
            int entityId1 = urlToEntityId1.get(sub);
            int entityId2 = urlToEntityId1.get(obj) + datasetLimit;`

Thanks !

**Comment by franklarryx** [comment]
Many thanks for the reply!
I had written wrong code.
My goal is to check how JedAI links the two datasets (source.nt and target.nt) in order to replace the silk tool!

kind regards,
Frank

**Comment by gpapadis** [comment]
You are welcome Frank! Let us know if we can assist you in any other way.

**Comment by franklarryx** [comment]
Hi George,

attached you can find the java class that you have provided to me, modified with block management and similarity process. 
I can't understand very well the result obtain from the class (result.txt in attached). I think that the percentages of similarity are not highly, but the linkage between datasets are present!

What do you think? Any suggestions?

Thanks in advance,
Frank


[classAndResult.zip](https://github.com/scify/JedAIToolkit/files/2061581/classAndResult.zip)

**Comment by gpapadis** [comment]
Hi Frank,

I am sorry for the late response. 

I updated the TestSilkData.java class (https://github.com/scify/JedAIToolkit/blob/mavenizedVersion/jedai-core/src/test/java/org/scify/jedai/datareader/TestSilkData.java) with a more complete version of the code. The code you sent me didn't perform Entity Clustering, which is necessary for yielding the final results. The absolute values of the similarities might be low, but what matters is their relative values. In the Clean-Clean ER scenario you are considering, Unique Mapping Clustering should be applied in the end so that for every entity, the best match is selected (i.e., the pair with the highest similarity), as long as this similarity exceeds a certain threshold. 

Note that the new code tests a large number of configurations in order to find the one with the highest performance. As a result, it will take some time to complete. I ran it, but no meaningful results were produced, because the ground-truth reader cannot extract any pair of duplicates from the source.nt file that is used as the source of the groundtruth.

Kind regards,
George

**Comment by franklarryx** [comment]
Thank you for your time!
Where can I find a simple example in rdf in order to better understand your tool?

Kind regards,
Frank

**Comment by mthanos** [comment]
Hi Frank,

You can find many relevant datasets here 
http://oaei.ontologymatching.org/2009/ ,
where we have also taken many of our benchmarks from.

You can also check the following datasets along with the expected mappings:
[oaeiIMidentity.zip](https://github.com/scify/JedAIToolkit/files/2089864/oaeiIMidentity.zip)
They were used for OAEI instance matching track (http://oaei.ontologymatching.org/2014/im/index.html)

Best regards,
Manos.

**Comment by franklarryx** [comment]
Many thanks for the indications and suggestions!

Kind regards,
Frank
