### ISSUE TITLE
Docker's Web Application gets stuck in Data Reading Phase

### ISSUE THREAD

**Issue by rusnov** [scify/JedAIToolkit#33]
I get the following error in the terminal after specifying input sources and then pressing "Next" button in Data Reading Step:

```
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Character
	at kr.di.uoa.gr.jedaiwebapp.models.Dataset.<init>(Dataset.java:86) ~[classes!/:0.0.1-SNAPSHOT]
	at kr.di.uoa.gr.jedaiwebapp.controllers.WorkflowController.validate_DataRead(WorkflowController.java:75) ~[classes!/:0.0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
...
```

**Comment by GiorgosMandi** [comment]
Hello, please test your experiment again with the updated version of the JedAI-Webapp docker

**Comment by vromaniello** [comment]
> I get the following error after specifying input sources and then pressing "Next" button in Data Reading Step in JedAI UI:
> 
> ```
> The input files could not be read successfully.
> 
> Details: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Character
> cannot be cast to java.lang.String (java.lang.Character cannot be cast to cast to java.lang.String)
> ```
> 
> In the terminal of Docker's Web Application I have the following:
> 
> ```
> java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Character
> 	at kr.di.uoa.gr.jedaiwebapp.models.Dataset.<init>(Dataset.java:86) ~[classes!/:0.0.1-SNAPSHOT]
> 	at kr.di.uoa.gr.jedaiwebapp.controllers.WorkflowController.validate_DataRead(WorkflowController.java:75) ~[classes!/:0.0.1-SNAPSHOT]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
> 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
> ...
> ```

Hi, then you solved? I have the same problem using [JedAI-gui](https://github.com/scify/JedAIToolkit/blob/master/jedai-ui.7z)
