### ISSUE TITLE
ArrayIndexOutOfBoundsException when blocking with schema clusters

### ISSUE THREAD

**Issue by saphyll** [scify/JedAIToolkit#38]
I got the following error when I tried blocking with schema clusters:
`java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.scify.jedai.blockbuilding.AbstractBlockBuilding.lambda$parseIndex$10(AbstractBlockBuilding.java:167)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at org.scify.jedai.blockbuilding.AbstractBlockBuilding.parseIndex(AbstractBlockBuilding.java:164)
	at org.scify.jedai.blockbuilding.AbstractBlockBuilding.readBlocks(AbstractBlockBuilding.java:196)
	at org.scify.jedai.blockbuilding.AbstractBlockBuilding.getBlocks(AbstractBlockBuilding.java:96)
	at org.scify.jedai.gui.utilities.WorkflowManager.runBlockBuilding(WorkflowManager.java:824)
	at org.scify.jedai.gui.utilities.WorkflowManager.runBlockingBasedWorkflow(WorkflowManager.java:896)
	at org.scify.jedai.gui.utilities.WorkflowManager.executeFullBlockingBasedWorkflow(WorkflowManager.java:393)
	at org.scify.jedai.gui.utilities.WorkflowManager.executeFullWorkflow(WorkflowManager.java:695)
	at org.scify.jedai.gui.controllers.steps.CompletedController.lambda$runAlgorithmBtnHandler$6(CompletedController.java:316)
	at java.base/java.lang.Thread.run(Thread.java:834)`

There is a String split operation in the parseIndex function, that is not working properly:
`final String[] entropyString = key.split(CLUSTER_SUFFIX);`
The delimiters used in `key`are equivalent to `CLUSTER_PREFIX`, not `CLUSTER_SUFFIX`, and they contain a dollar-sign that has to be escaped. I worked around the issue by changing the above line to 
`final String[] entropyString = key.split("#\\$!cl");`

I'd suggest changing the values of the prefix and suffix to something that is compatible with regex - the solution above is less readable after all.

**Comment by gpapadis** [comment]
Thank you indeed for the recommendation. Schema clustering is work in progress, so there are likely to be more bugs in the code. If your data do not contain large, heterogeneous schemata, we recommend skipping Schema Clustering for the time being.
