### ISSUE TITLE
Unable to Read csv or json files 

### ISSUE THREAD

**Issue by faisalkhalikkhan** [scify/JedAIToolkit#61]
I have my own custom data csv files for both dataset as well as ground truth file,
can anyone help me to use this file to get result.
Actually it throw some errors while using this files as an input.

`Exception in thread "main" java.lang.IllegalArgumentException: loops not allowed
        at org.jgrapht.graph.AbstractBaseGraph.addEdge(AbstractBaseGraph.java:218)
        at org.scify.jedai.datareader.groundtruthreader.GtCSVReader.getDuplicatePairs(GtCSVReader.java:206)
        at org.scify.jedai.datareader.groundtruthreader.AbstractGtReader.getDuplicatePairs(AbstractGtReader.java:58)
        at org.scify.jedai.workflowbuilder.Main.main(Main.java:254)` 

can anyone help me?

**Comment by gpapadis** [comment]
HI! 
I am sorry for the late reply. What kind of dataset are you trying to use? A dirty er or a clean-clean ER one? 
This error is thrown when JedAI cannot read the dataset correctly and assigns the same id (0) to all entities. 
Check these issues 
1) https://github.com/scify/JedAIToolkit/issues/19 
2) https://github.com/scify/JedAIToolkit/issues/60
for some hints on using CSV files with JedAI.
